<?php
use App\Crawler\OpenDir;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-16 at 20:12:46.
 */
class OpenDirCrawlerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var OpenDir
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OpenDir('app');
    }

    /**
     * @covers App\Crawler\OpenDir::walk
     */
    public function testWalk()
    {
        $count = 0;

        $this->object->walk(function($file) use (&$count) {

            $this->assertFileExists('app/' . $file);

            $count++;

        });

        $this->assertTrue($count > 0);
    }
}
